[package]
name = "nodejs"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.106"
sqlite-wasm-rs = { path = "../.." }
wasm-bindgen-futures = "0.4.55"

[lib]
crate-type = ["cdylib"]
