name: counter
publish_to: "none"

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar_plus: ^1.1.9
  isar_plus_flutter_libs: ^1.1.9
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.10.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
