name: isar_plus_inspector
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clickup_fading_scroll:
    git:
      url: https://github.com/clickup/clickup_fading_scroll
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.12.0
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  isar_plus: ^1.2.2
  vm_service: ^15.0.2
  web: ^1.1.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
